# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddcat < Formula
  desc "CLI to display Datadog Logs."
  homepage "https://github.com/kanmu/ddcat"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/ddcat/releases/download/v0.2.0/ddcat_0.2.0_darwin_amd64.tar.gz"
      sha256 "0b82bfa0f87d8fe708b00279163fccbecc0a32b0eba0a62f8779b5ca0519c775"

      def install
        bin.install 'ddcat'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/ddcat/releases/download/v0.2.0/ddcat_0.2.0_darwin_arm64.tar.gz"
      sha256 "35a16eaefe0b9db5446c67b685ba4dbd953fb4df27c6c63851385403561146b2"

      def install
        bin.install 'ddcat'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/ddcat/releases/download/v0.2.0/ddcat_0.2.0_linux_amd64.tar.gz"
      sha256 "442645d11a62f7a7658edfaaa9eb575df5d0902c1f4e09ded652c9b95fbfb72e"

      def install
        bin.install 'ddcat'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/ddcat/releases/download/v0.2.0/ddcat_0.2.0_linux_arm64.tar.gz"
      sha256 "6ee712ef6a055f7f63b3d507f37a8032802ba4f038945cb61ad76f96f9429509"

      def install
        bin.install 'ddcat'
      end
    end
  end
end
