# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demitas2 < Formula
  desc "Wrapper for ecspresso that creates task definitions at run time."
  homepage "https://github.com/kanmu/demitas2"
  version "4.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/demitas2/releases/download/v4.0.0/demitas2_4.0.0_darwin_arm64.tar.gz"
      sha256 "f864f21fbf0b70572097a6990aa332d7839b67d4fb2433b382bf2e12a29f3b50"

      def install
        bin.install 'dmts'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/demitas2/releases/download/v4.0.0/demitas2_4.0.0_darwin_amd64.tar.gz"
      sha256 "ba3d5b133fbcd0d9edcde1697e525f5ecf3a82cb617d1844e681e3d4cd76f5d3"

      def install
        bin.install 'dmts'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/demitas2/releases/download/v4.0.0/demitas2_4.0.0_linux_amd64.tar.gz"
      sha256 "73e4f4c9c1447309eba28885413537318f647ac3758c6ed19a4d95977b088660"

      def install
        bin.install 'dmts'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/demitas2/releases/download/v4.0.0/demitas2_4.0.0_linux_arm64.tar.gz"
      sha256 "04139811e328a8c6bbb0a8eae8c18ccf61a985abeef11963305b9ea7bba1f60f"

      def install
        bin.install 'dmts'
      end
    end
  end
end
