# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dgw < Formula
  desc "dgw generates Golang struct, and simple Table/Row Data Gateway functions from PostgreSQL table metadata"
  homepage "https://github.com/kanmu/dgw"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/dgw/releases/download/v1.2.0/dgw_1.2.0_darwin_arm64.tar.gz"
      sha256 "aa58e14ebb756a8c4f7315d0775d281206116356fae39dd4383a64906fc23689"

      def install
        bin.install 'dgw'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/dgw/releases/download/v1.2.0/dgw_1.2.0_darwin_amd64.tar.gz"
      sha256 "09856ba6a1236da42a9e69decd03a8ce07df86fb627a843c13eb5f16e13cba43"

      def install
        bin.install 'dgw'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/dgw/releases/download/v1.2.0/dgw_1.2.0_linux_arm64.tar.gz"
      sha256 "186c01b4df877baa1c3b708110e34ab68491bc31966165a9871dd445488b1ef4"

      def install
        bin.install 'dgw'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/dgw/releases/download/v1.2.0/dgw_1.2.0_linux_amd64.tar.gz"
      sha256 "e906e38790a406160b3b9110980fba3a8f19a2596ada92cd01c6f4cdcc5015ef"

      def install
        bin.install 'dgw'
      end
    end
  end
end
