# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dgw < Formula
  desc "dgw generates Golang struct, and simple Table/Row Data Gateway functions from PostgreSQL table metadata"
  homepage "https://github.com/kanmu/dgw"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/dgw/releases/download/v1.5.0/dgw_1.5.0_darwin_amd64.tar.gz"
      sha256 "71d3b5c240248531a0fbdb29e1847fdee9a001efedf3b2255dc1cf8ec2db128e"

      define_method(:install) do
        bin.install 'dgw'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/dgw/releases/download/v1.5.0/dgw_1.5.0_darwin_arm64.tar.gz"
      sha256 "a91136e71210f0f43acddbc4658d5da1e0d94b03415eea5ff8ec3fafc969b8ac"

      define_method(:install) do
        bin.install 'dgw'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/dgw/releases/download/v1.5.0/dgw_1.5.0_linux_amd64.tar.gz"
      sha256 "2bf74e79e9b98c57eed1a7b5eaff98bc43d540957453b3247d0267bfe938b6cf"
      define_method(:install) do
        bin.install 'dgw'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/dgw/releases/download/v1.5.0/dgw_1.5.0_linux_arm64.tar.gz"
      sha256 "8e58d58afab545f58184d24fbe710c00bbe9f4232c86e8bb114a5bd0492f29d9"
      define_method(:install) do
        bin.install 'dgw'
      end
    end
  end
end
