# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jhol < Formula
  desc "CLI to display and check Japanese holidays."
  homepage "https://github.com/kanmu/jhol"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/jhol/releases/download/v2.0.0/jhol_2.0.0_darwin_amd64.tar.gz"
      sha256 "f7dc6fd8f833b69e879c52de82c3253d456377426dc864d5db4b6341f9a0700f"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/jhol/releases/download/v2.0.0/jhol_2.0.0_darwin_arm64.tar.gz"
      sha256 "12bdb239f7ede1bb7851f124f883e5b62156c437305904f80c6e687e07585ef0"

      def install
        bin.install 'jhol'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/jhol/releases/download/v2.0.0/jhol_2.0.0_linux_amd64.tar.gz"
      sha256 "874cc95c7427b854758e59e7523dd51bd98b49d4cc5df2180a8bd2bf408d11b6"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/jhol/releases/download/v2.0.0/jhol_2.0.0_linux_arm64.tar.gz"
      sha256 "f7db2f59a19f29f5b25435bd4ad85aae158b5ba1f65a7e7866bd0b388dcdc694"

      def install
        bin.install 'jhol'
      end
    end
  end
end
