# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jhol < Formula
  desc "CLI to display and check Japanese holidays."
  homepage "https://github.com/kanmu/jhol"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/jhol/releases/download/v2.2.0/jhol_2.2.0_darwin_amd64.tar.gz"
      sha256 "7bd1f669e4d1e04674cc8cb0de7f2c199511230aa6d95feb8e4187de1ef4364b"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/jhol/releases/download/v2.2.0/jhol_2.2.0_darwin_arm64.tar.gz"
      sha256 "8568811c49f7bec8b57906cb4aa3d3a8b2621df26b8a9db9368f7e2027c7609c"

      def install
        bin.install 'jhol'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/jhol/releases/download/v2.2.0/jhol_2.2.0_linux_arm64.tar.gz"
      sha256 "210bcef33e2d41dbd717a2bf0d00294e06061465e294d9f2234e5c90cfb0f281"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/jhol/releases/download/v2.2.0/jhol_2.2.0_linux_amd64.tar.gz"
      sha256 "54ed5c5017136a8689ac0df54e9cd70f527467615f888205fdd4a22b39d40619"

      def install
        bin.install 'jhol'
      end
    end
  end
end
