# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kasa < Formula
  desc "CLI for esa."
  homepage "https://github.com/kanmu/kasa"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/kasa/releases/download/v1.1.0/kasa_1.1.0_darwin_amd64.tar.gz"
      sha256 "8061f01a3d0cb797478c1f271c12a1a4eb9544c63da9d0b2eb48eb8b9fa2b967"

      def install
        bin.install 'kasa'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/kasa/releases/download/v1.1.0/kasa_1.1.0_darwin_arm64.tar.gz"
      sha256 "40c5ae6f137c9a523fdae69ebc4c3c9d778ac5b6851de6716014451a93df1c05"

      def install
        bin.install 'kasa'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/kasa/releases/download/v1.1.0/kasa_1.1.0_linux_arm64.tar.gz"
      sha256 "165580d969fbcf055d32fe0c94758737a7228b7b2fd98c409c893306c611095c"

      def install
        bin.install 'kasa'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/kasa/releases/download/v1.1.0/kasa_1.1.0_linux_amd64.tar.gz"
      sha256 "34b4e3afc20af23b4ef99a2f0ae2dab7a0fe07d02fb0ab5728da9dd7746c31d5"

      def install
        bin.install 'kasa'
      end
    end
  end
end
