# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kasa < Formula
  desc "CLI for esa."
  homepage "https://github.com/kanmu/kasa"
  version "1.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/kasa/releases/download/v1.3.5/kasa_1.3.5_darwin_amd64.tar.gz"
      sha256 "0237e20e9463ac32d64beab20937176a5159c4af8b85d3d61adf56a0ed775d26"

      def install
        bin.install 'kasa'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/kasa/releases/download/v1.3.5/kasa_1.3.5_darwin_arm64.tar.gz"
      sha256 "7001c779b65201827c60d8d90e3e546d80f08254162dccfd4faedaab654f4224"

      def install
        bin.install 'kasa'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/kasa/releases/download/v1.3.5/kasa_1.3.5_linux_amd64.tar.gz"
      sha256 "27460d75c471b82db1686ca306d00e08cc2e0cbc5f3bd7f4faf925cb940e0e21"

      def install
        bin.install 'kasa'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/kasa/releases/download/v1.3.5/kasa_1.3.5_linux_arm64.tar.gz"
      sha256 "2a4bdc77ea0a606dbe1bf0fc15e1e69dd0a173905a6d3d4ea3346d0d8e692747"

      def install
        bin.install 'kasa'
      end
    end
  end
end
