# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kasa < Formula
  desc "CLI for esa."
  homepage "https://github.com/kanmu/kasa"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/kasa/releases/download/v1.3.3/kasa_1.3.3_darwin_arm64.tar.gz"
      sha256 "7256bdeec11a42ca9b5411898a67b0e909bfbbeaf3264b2103f4ceefb5c520ac"

      def install
        bin.install 'kasa'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/kasa/releases/download/v1.3.3/kasa_1.3.3_darwin_amd64.tar.gz"
      sha256 "ac95953ab8bd6d5c312f28949844a4bbdbf2e8ebab210c1268c683a5fc5ddd5c"

      def install
        bin.install 'kasa'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/kasa/releases/download/v1.3.3/kasa_1.3.3_linux_amd64.tar.gz"
      sha256 "ed74fafd9b1c6a212427c351117985e2843f142dc42b357f59053c497ccb29d2"

      def install
        bin.install 'kasa'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/kasa/releases/download/v1.3.3/kasa_1.3.3_linux_arm64.tar.gz"
      sha256 "9aff9fb3f04f0042a315315c57699ddae75ab97b381322c14782cee95b3c64ff"

      def install
        bin.install 'kasa'
      end
    end
  end
end
