# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prmdg < Formula
  desc "prmd style JSON Hyper Schema to Go structs, and validators"
  homepage "https://github.com/kanmu/prmdg"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/prmdg/releases/download/v0.2.0/prmdg_0.2.0_darwin_arm64.tar.gz"
      sha256 "193590d49e6533666dd0eef108eeffcef9b8f93989609aa511ead0bce74f307f"

      def install
        bin.install 'prmdg'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/prmdg/releases/download/v0.2.0/prmdg_0.2.0_darwin_amd64.tar.gz"
      sha256 "54c8abc4cc3b0e3e46d53b0bddbe1265fe45bebee574616967215efa79bdb24e"

      def install
        bin.install 'prmdg'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/prmdg/releases/download/v0.2.0/prmdg_0.2.0_linux_amd64.tar.gz"
      sha256 "6043805630a0707eb3e13a6343ea02454da01123f4069f58579df23adaefc0cb"

      def install
        bin.install 'prmdg'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/prmdg/releases/download/v0.2.0/prmdg_0.2.0_linux_arm64.tar.gz"
      sha256 "f4f8056975d7bc7ff12828c56b53db105e56825b8ff9c1009a67c82ac3b1e707"

      def install
        bin.install 'prmdg'
      end
    end
  end
end
