# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prmdg < Formula
  desc "prmd style JSON Hyper Schema to Go structs, and validators"
  homepage "https://github.com/kanmu/prmdg"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/prmdg/releases/download/v1.0.0/prmdg_1.0.0_darwin_amd64.tar.gz"
      sha256 "aefe5bf175d11e300361ccae6b403a73a09438b19550c3f36760a3053ca319c2"

      def install
        bin.install 'prmdg'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanmu/prmdg/releases/download/v1.0.0/prmdg_1.0.0_darwin_arm64.tar.gz"
      sha256 "74a32549593fa7ddab7e211f6c38d5225123a04e1de7f95e751597d5939de0d7"

      def install
        bin.install 'prmdg'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanmu/prmdg/releases/download/v1.0.0/prmdg_1.0.0_linux_arm64.tar.gz"
      sha256 "c8bcaaf1ca7e5c4dc37bb47ecc48e2b70d474ba53cabae55ad69b648b03dc05b"

      def install
        bin.install 'prmdg'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kanmu/prmdg/releases/download/v1.0.0/prmdg_1.0.0_linux_amd64.tar.gz"
      sha256 "1b21b736d7898d51f3e0dac69500b31178c462805fefabcfc9a16b15f531e6ee"

      def install
        bin.install 'prmdg'
      end
    end
  end
end
