# This file was generated by GoReleaser. DO NOT EDIT.
cask "demitas2" do
  version "5.3.0"

  on_macos do
    on_intel do
      sha256 "8e86f575cb6f3988693d9883958abe9a6fc71ed09f77a80bffdea2179ace2575"
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9db02f5b5a2ae09fb7cd1b467121b1f661e807e6be6a3a1c04e072fa4f28bb5"
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "13d36dbdf62018f5fd3e3c09cb56fd473b69ebf61bbee14ceaa20db540989d72"
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ab538c9ac5a2f37cb411167dd82bf8d01d2816c274595c368a81451b3fc8057"
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_linux_arm64.tar.gz"
    end
  end

  name "demitas2"
  desc "Wrapper for ecspresso that creates task definitions at run time."
  homepage "https://github.com/kanmu/demitas2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dmts"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dmts"]
    end
  end

  # No zap stanza required

end
