# This file was generated by GoReleaser. DO NOT EDIT.
cask "demitas2" do
  name "demitas2"
  desc "Wrapper for ecspresso that creates task definitions at run time."
  homepage "https://github.com/kanmu/demitas2"
  version "5.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dmts"

  on_macos do
    on_intel do
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_darwin_amd64.tar.gz"
      sha256 "9fef2e3fffffb1d6f823f415de6bcfaec80fd6de76621eb2302ad5813d89caa1"
    end
    on_arm do
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_darwin_arm64.tar.gz"
      sha256 "4c620de1ab1d95dcfcdd30facc801147a3a7521c4635d4089f0ebf33b0e3871f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_linux_amd64.tar.gz"
      sha256 "99bc66d5d05108439697f89125ac59eae9b4bc23d2f44d87ad524d584f519c2e"
    end
    on_arm do
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_linux_arm64.tar.gz"
      sha256 "91737ce48c90f3627334dc5fd1416e83882a0ab6e7e14327b704cc98165f89e9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dmts"]
    end
  end

  # No zap stanza required
end
