# This file was generated by GoReleaser. DO NOT EDIT.
cask "demitas2" do
  name "demitas2"
  desc "Wrapper for ecspresso that creates task definitions at run time."
  homepage "https://github.com/kanmu/demitas2"
  version "5.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "demitas2"

  on_macos do
    on_intel do
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_darwin_amd64.tar.gz"
      sha256 "ea12e553eaff47918be4383878bc297a4d96f23bfe7ca3e5d93c40a11649f25f"
    end
    on_arm do
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_darwin_arm64.tar.gz"
      sha256 "dc5ca932285b018f7a9add4e60deb8cc4dfe781eb58f88bafdd9fc75ae53b59d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_linux_amd64.tar.gz"
      sha256 "f148ad4407071699899ac7580bc83d234663460853c5c0f94eaf9dbed926c805"
    end
    on_arm do
      url "https://github.com/kanmu/demitas2/releases/download/v#{version}/demitas2_#{version}_linux_arm64.tar.gz"
      sha256 "5dbed8df3707cd8a484b1461a7d072a0be1fa18aa670a07ab6f38f17cde6aec9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dmts"]
    end
  end

  # No zap stanza required
end
